// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Css from "bs-css-emotion/lib/es6/src/Css.bs.js";
import * as List from "bs-platform/lib/es6/list.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Css_Legacy_Core from "bs-css/lib/es6/src/Css_Legacy_Core.bs.js";

function button(disabled) {
  var baseStyles_0 = Css.borderRadius(Css.px(5));
  var baseStyles_1 = {
    hd: Css.padding(Css.px(10)),
    tl: {
      hd: Css.borderWidth(Css.px(0)),
      tl: {
        hd: Css.backgroundColor(Css.hex("#fff")),
        tl: {
          hd: Css.margin(Css.em(1)),
          tl: {
            hd: Css.boxShadow(Css_Legacy_Core.Shadow.box(undefined, Css.px(3), Css.px(5), undefined, undefined, Css.rgba(0, 0, 0, {
                          NAME: "num",
                          VAL: 0.3
                        }))),
            tl: {
              hd: Css.active({
                    hd: Css.outline(Css.px(0), "solid", Css.black),
                    tl: /* [] */0
                  }),
              tl: /* [] */0
            }
          }
        }
      }
    }
  };
  var baseStyles = {
    hd: baseStyles_0,
    tl: baseStyles_1
  };
  if (disabled) {
    return Curry._1(Css.style, List.concat({
                    hd: baseStyles,
                    tl: {
                      hd: {
                        hd: Css.cursor("default"),
                        tl: /* [] */0
                      },
                      tl: /* [] */0
                    }
                  }));
  } else {
    return Curry._1(Css.style, List.concat({
                    hd: baseStyles,
                    tl: {
                      hd: {
                        hd: Css.cursor(Css.pointer),
                        tl: {
                          hd: Css.hover({
                                hd: Css.boxShadow(Css_Legacy_Core.Shadow.box(undefined, Css.px(5), Css.px(8), undefined, undefined, Css.rgba(0, 0, 0, {
                                              NAME: "num",
                                              VAL: 0.3
                                            }))),
                                tl: /* [] */0
                              }),
                          tl: /* [] */0
                        }
                      },
                      tl: /* [] */0
                    }
                  }));
  }
}

var Styles = {
  button: button
};

function Button(Props) {
  var children = Props.children;
  var onClick = Props.onClick;
  var disabled = Props.disabled;
  return React.createElement("button", {
              className: button(disabled),
              disabled: disabled,
              onClick: onClick
            }, children);
}

var make = Button;

export {
  Styles ,
  make ,
  
}
/* Css Not a pure module */
