// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Css from "bs-css-emotion/lib/es6/src/Css.bs.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

var background = Curry._1(Css.style, {
      hd: Css.backgroundColor(Css.hex("aff")),
      tl: {
        hd: Css.display("flex"),
        tl: {
          hd: Css.flexDirection("column"),
          tl: {
            hd: Css.justifyContent("flexStart"),
            tl: {
              hd: Css.alignItems("center"),
              tl: {
                hd: Css.height(Css.vh(100)),
                tl: {
                  hd: Css.width(Css.vw(100)),
                  tl: {
                    hd: Css.padding(Css.rem(2)),
                    tl: /* [] */0
                  }
                }
              }
            }
          }
        }
      }
    });

var Styles = {
  background: background
};

function Background(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: background
            }, children);
}

var make = Background;

export {
  Styles ,
  make ,
  
}
/* background Not a pure module */
