// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Array from "bs-platform/lib/es6/array.js";

function concat(array1, array2) {
  return $$Array.concat({
              hd: array1,
              tl: {
                hd: array2,
                tl: /* [] */0
              }
            });
}

function updateElementInArray(array, index, newValue) {
  var lengthOfArray = array.length;
  return concat(concat(array.slice(0, index), [newValue]), array.slice(index + 1 | 0, lengthOfArray - 1 | 0));
}

export {
  concat ,
  updateElementInArray ,
  
}
/* No side effect */
